In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
survey_patient = pd.read_csv("HCAHPS-CA-Hospital.csv",encoding='latin-1')
updated_sp = survey_patient.drop(["ZIP Code","Phone Number", "Patient Survey Star Rating Footnote","HCAHPS Answer Percent Footnote","Number of Completed Surveys Footnote","HCAHPS Answer Percent","HCAHPS Linear Mean Value","Survey Response Rate Percent Footnote","Measure Start Date", "Measure End Date"], axis=1)
#updated_sp_na = updated_sp.drop(updated_sp[updated_sp["Patient Survey Star Rating"] == "Not Available"].index)
updated_sp_naa = updated_sp.drop(updated_sp[updated_sp["Patient Survey Star Rating"] == "Not Applicable"].index)
updated_sp_naa.head()

,Provider ID,Hospital Name,Address,City,State,County Name,HCAHPS Measure ID,HCAHPS Question,HCAHPS Answer Description,Patient Survey Star Rating,Number of Completed Surveys,Survey Response Rate Percent
0,50002,ST ROSE HOSPITAL,27200 CALAROGA AVE,HAYWARD,CA,ALAMEDA,H_STAR_RATING,Summary star rating,Summary star rating,2,614,22
5,50002,ST ROSE HOSPITAL,27200 CALAROGA AVE,HAYWARD,CA,ALAMEDA,H_CLEAN_STAR_RATING,Cleanliness - star rating,Cleanliness - star rating,2,614,22
9,50002,ST ROSE HOSPITAL,27200 CALAROGA AVE,HAYWARD,CA,ALAMEDA,H_COMP_1_STAR_RATING,Nurse communication - star rating,Nurse communication - star rating,2,614,22
14,50002,ST ROSE HOSPITAL,27200 CALAROGA AVE,HAYWARD,CA,ALAMEDA,H_COMP_2_STAR_RATING,Doctor communication - star rating,Doctor communication - star rating,2,614,22
19,50002,ST ROSE HOSPITAL,27200 CALAROGA AVE,HAYWARD,CA,ALAMEDA,H_COMP_3_STAR_RATING,Staff responsiveness - star rating,Staff responsiveness - star rating,2,614,22

In [4]:
all_rating = updated_sp_naa.pivot(index='Provider ID', columns='HCAHPS Measure ID', values='Patient Survey Star Rating').reset_index()
all_rating.head()

HCAHPS Measure ID,Provider ID,H_CLEAN_STAR_RATING,H_COMP_1_STAR_RATING,H_COMP_2_STAR_RATING,H_COMP_3_STAR_RATING,H_COMP_4_STAR_RATING,H_COMP_5_STAR_RATING,H_COMP_6_STAR_RATING,H_COMP_7_STAR_RATING,H_HSP_RATING_STAR_RATING,H_QUIET_STAR_RATING,H_RECMND_STAR_RATING,H_STAR_RATING
0,50002,2,2,2,2,2,2,2,1,2,2,2,2
1,50006,2,2,2,2,3,2,3,2,2,1,3,2
2,50007,3,4,3,3,4,3,3,4,5,3,5,4
3,50008,2,2,3,2,3,2,2,2,3,1,3,2
4,50009,2,3,3,3,3,3,3,2,3,1,3,3

In [5]:
basic_info = updated_sp_naa.drop(["HCAHPS Measure ID","HCAHPS Question","HCAHPS Answer Description","Patient Survey Star Rating","Number of Completed Surveys","Survey Response Rate Percent"], axis=1)
basic_information = basic_info.drop_duplicates()
merged_rating = pd.merge(all_rating, basic_information, how="left", on="Provider ID")
merged_rating.rename(columns={"H_CLEAN_STAR_RATING": "Cleanliness", 
                              "H_COMP_1_STAR_RATING":"Nurse_com", 
                              "H_COMP_2_STAR_RATING":"Doc_com", 
                              "H_COMP_3_STAR_RATING":"Staff_responsiveness",
                              "H_COMP_4_STAR_RATING": "Pain_management",
                              "H_COMP_5_STAR_RATING": "Comm_medicine", 
                              "H_COMP_6_STAR_RATING":"Discharge_info", 
                              "H_COMP_7_STAR_RATING": "Care_transition", 
                              "H_HSP_RATING_STAR_RATING": "Overall_Hos_Rating", 
                              "H_QUIET_STAR_RATING": "Quietness", 
                              "H_RECMND_STAR_RATING": "Recomm_hos", 
                              "H_STAR_RATING": "Summary_star"})
merged_rating.to_csv("Hospital Rating.csv")