In [1]:
import pandas as pd
import numpy as np
import csv

In [2]:
Hospital_merged_pd = pd.read_csv("Hospital_Merged_CleanNoIndex.csv")

In [3]:
Hospital_merged_pd.head(5)

,Provider ID,Cleanliness,Nurse_com,Doc_com,Staff_responsiveness,Pain_management,Comm_medicine,Discharge_info,Care_transition,Overall_Hos_Rating,...,Summary_star,Hospital Name,Address,City,State,County Name,ZIP Code,Phone Number,Hospital Type,Hospital Ownership
0,50002,2,2,2,2,2,2,2,1,2,...,2,ST ROSE HOSPITAL,27200 CALAROGA AVE,HAYWARD,CA,ALAMEDA,94545,5107826200,Acute Care Hospitals,Voluntary non-profit - Church
1,50006,2,2,2,2,3,2,3,2,2,...,2,ST JOSEPH HOSPITAL,2700 DOLBEER ST,EUREKA,CA,HUMBOLDT,95501,7074458121,Acute Care Hospitals,Voluntary non-profit - Private
2,50007,3,4,3,3,4,3,3,4,5,...,4,MILLS-PENINSULA MEDICAL CENTER,1501 TROUSDALE DRIVE,BURLINGAME,CA,SAN MATEO,94010,6506965270,Acute Care Hospitals,Voluntary non-profit - Private
3,50008,2,2,3,2,3,2,2,2,3,...,2,CALIFORNIA PACIFIC MEDICAL CTR-DAVIES CAMPUS HOSP,601 DUBOCE AVE,SAN FRANCISCO,CA,SAN FRANCISCO,94117,4156006000,Acute Care Hospitals,Voluntary non-profit - Other
4,50009,2,3,3,3,3,3,3,2,3,...,3,QUEEN OF THE VALLEY MEDICAL CENTER,1000 TRANCAS ST,NAPA,CA,NAPA,94558,7072524411,Acute Care Hospitals,Voluntary non-profit - Church

In [4]:
Hospital_merged_pd = Hospital_merged_pd[Hospital_merged_pd.Overall_Hos_Rating != "Not Available"]

In [5]:
Hospital_merged_pd["Overall_Hos_Rating"] = Hospital_merged_pd["Overall_Hos_Rating"].astype("float")

In [6]:
County_ratings = Hospital_merged_pd.groupby("County Name")

In [7]:
# Calculate Stanadard Deviation of the Overall Hospital Ratings per county.
round(County_ratings["Overall_Hos_Rating"].std(), 2)

County Name
ALAMEDA            0.67
AMADOR              NaN
BUTTE              2.00
CALAVERAS           NaN
CONTRA COSTA       1.00
DEL NORTE           NaN
EL DORADO          0.00
FRESNO             0.82
HUMBOLDT           0.71
IMPERIAL           0.00
INYO                NaN
KERN               0.98
KINGS               NaN
LAKE               0.71
LASSEN              NaN
LOS ANGELES        1.16
MADERA              NaN
MARIN              0.58
MENDOCINO          1.53
MERCED             0.00
MONO                NaN
MONTEREY           0.82
NAPA               0.00
NEVADA             2.12
ORANGE             1.31
PLACER             0.58
RIVERSIDE          1.24
SACRAMENTO         0.71
SAN BENITO          NaN
SAN BERNARDINO     0.92
SAN DIEGO          0.96
SAN FRANCISCO      0.87
SAN JOAQUIN        0.76
SAN LUIS OBISPO    0.58
SAN MATEO          1.05
SANTA BARBARA      1.29
SANTA CLARA        0.78
SANTA CRUZ         1.53
SHASTA             0.71
SISKIYOU           0.00
SOLANO             0.82
SONOMA             0.75
STANISLAUS         1.22
SUTTER              NaN
TEHAMA              NaN
TULARE             1.15
TUOLUMNE            NaN
VENTURA            0.69
YOLO               1.41
YUBA                NaN
Name: Overall_Hos_Rating, dtype: float64

In [29]:
# Create a Data Frame for the Standard Deviation data
StdDevofRatings_County = pd.DataFrame(round(County_ratings["Overall_Hos_Rating"].std(), 2))
# Drop all NaN values (Standard Devation is NaN because there is only 1 city with data for that county)
#StdDevofRatings_County = StdDevofRatings_County[str(StdDevofRatings_County.Overall_Hos_Rating)!= "NaN"]
#Hospital_merged_pd = Hospital_merged_pd[Hospital_merged_pd.Overall_Hos_Rating != "Not Available"]
StdDevofRatings_County

                 Overall_Hos_Rating
County Name
ALAMEDA                        0.67
AMADOR                          NaN
BUTTE                          2.00
CALAVERAS                       NaN
CONTRA COSTA                   1.00
DEL NORTE                       NaN
EL DORADO                      0.00
FRESNO                         0.82
HUMBOLDT                       0.71
IMPERIAL                       0.00
INYO                            NaN
KERN                           0.98
KINGS                           NaN
LAKE                           0.71
LASSEN                          NaN
LOS ANGELES                    1.16
MADERA                          NaN
MARIN                          0.58
MENDOCINO                      1.53
MERCED                         0.00
MONO                            NaN
MONTEREY                       0.82
NAPA                           0.00
NEVADA                         2.12
ORANGE                         1.31
PLACER                         0.58
RIVERSIDE                      1.24
SACRAMENTO                     0.71
SAN BENITO                      NaN
SAN BERNARDINO                 0.92
SAN DIEGO                      0.96
SAN FRANCISCO                  0.87
SAN JOAQUIN                    0.76
SAN LUIS OBISPO                0.58
SAN MATEO                      1.05
SANTA BARBARA                  1.29
SANTA CLARA                    0.78
SANTA CRUZ                     1.53
SHASTA                         0.71
SISKIYOU                       0.00
SOLANO                         0.82
SONOMA                         0.75
STANISLAUS                     1.22
SUTTER                          NaN
TEHAMA                          NaN
TULARE                         1.15
TUOLUMNE                        NaN
VENTURA                        0.69
YOLO                           1.41
YUBA                            NaN

In [30]:
# Convert the Hospital Rating Standard Deviation column into string
StdDevofRatings_County["Overall_Hos_Rating"] = StdDevofRatings_County["Overall_Hos_Rating"].astype("str")
# delete the rows with Standard Devaiation as NaN (after NaN is converted into string it is written as "nan")
StdDevofRatings_County = StdDevofRatings_County[StdDevofRatings_County.Overall_Hos_Rating != "nan"]
StdDevofRatings_County.columns = ["Std_Dev_Overall_Rating"]
StdDevofRatings_County

                Std_Dev_Overall_Rating
County Name
ALAMEDA                           0.67
BUTTE                              2.0
CONTRA COSTA                       1.0
EL DORADO                          0.0
FRESNO                            0.82
HUMBOLDT                          0.71
IMPERIAL                           0.0
KERN                              0.98
LAKE                              0.71
LOS ANGELES                       1.16
MARIN                             0.58
MENDOCINO                         1.53
MERCED                             0.0
MONTEREY                          0.82
NAPA                               0.0
NEVADA                            2.12
ORANGE                            1.31
PLACER                            0.58
RIVERSIDE                         1.24
SACRAMENTO                        0.71
SAN BERNARDINO                    0.92
SAN DIEGO                         0.96
SAN FRANCISCO                     0.87
SAN JOAQUIN                       0.76
SAN LUIS OBISPO                   0.58
SAN MATEO                         1.05
SANTA BARBARA                     1.29
SANTA CLARA                       0.78
SANTA CRUZ                        1.53
SHASTA                            0.71
SISKIYOU                           0.0
SOLANO                            0.82
SONOMA                            0.75
STANISLAUS                        1.22
TULARE                            1.15
VENTURA                           0.69
YOLO                              1.41

In [32]:
StdDevofRatings_County.to_csv("StdDev_Overall_Ratings_perCounty.csv")

In [31]:
#df.columns = ['a', 'b']
StdDevofRatings_County.columns

Index(['Std_Dev_Overall_Rating'], dtype='object')